quarkus:
  profile: test
  log:
    sentry:
      ~: false
      dsn: 'test'
      in-app-packages: com.axuanhogan
      environment: local
      level: ERROR
    level: INFO
    console:
      format: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{3.}:%L] [%X{REQUEST.ID}] %s%e%n'
  devservices:
    enabled: true
  datasource:
    db-kind: postgresql
    devservices:
      reuse: false
      port: 5434
      db-name: postgres
      username: quarkus
      password: quarkus
  liquibase:
    enabled: true
    migrate-at-start: true
    change-log: db/root.yaml
  hibernate-orm:
    packages:
      - 'com.axuanhogan.common.dao'
    log:
      sql: true
    schema-management:
      strategy: validate
  http:
    host: localhost
    access-log:
      enabled: true
    limits:
      max-body-size: 100M
  rest-client:
    connect-timeout: 15000
    read-timeout: 30000
mp:
  jwt:
    token:
      header: Cookie
      cookie: 'test'
    verify:
      issuer: 'test'
      audiences: 'test'
      publickey:
        location: 'test'
smallrye:
  jwt:
    always-check-authorization: true
application:
  domain-name: 'test-axuanhogan.com'
  dao:
    encryption:
      enabled: false
    aes:
      key: 'key'
      iv: 'iv'
